# Generated by Django 5.2.5 on 2026-02-05 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('ad_username', models.CharField(help_text='Active Directory username (e.g., mohamed.khaled)', max_length=100, unique=True, verbose_name='AD Username (sAMAccountName)')),
                ('first_name_en', models.CharField(max_length=100, verbose_name='First Name (English)')),
                ('last_name_en', models.CharField(max_length=100, verbose_name='Last Name (English)')),
                ('first_name_ar', models.CharField(max_length=100, verbose_name='First Name (Arabic)')),
                ('last_name_ar', models.CharField(max_length=100, verbose_name='Last Name (Arabic)')),
                ('job_title', models.CharField(max_length=150, verbose_name='Job Title')),
                ('department', models.CharField(choices=[('IT', 'IT (تكنولوجيا المعلومات)'), ('HR', 'HR (الموارد البشرية)'), ('Accountant', 'Accountant (المحاسبة)'), ('Administrative Affairs', 'Administrative Affairs (الشؤون الإدارية)'), ('Camera', 'Camera (الكاميرات)'), ('Exhibit', 'Exhibit (المعارض)'), ('Audit', 'Audit (المراجعة)'), ('Out Work', 'Out Work (العمل الخارجي)'), ('Projects', 'Projects (المشاريع)'), ('Sales', 'Sales (المبيعات)'), ('Supplies', 'Supplies (المشتريات)'), ('Secretarial', 'Secretarial (السكرتارية)')], max_length=100, verbose_name='Department')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 14 digits', regex='^\\d{14}$')], verbose_name='National ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ad_username'], name='employees_ad_user_965d5b_idx'), models.Index(fields=['national_id'], name='employees_nationa_268f02_idx'), models.Index(fields=['department'], name='employees_departm_ef7a1f_idx')],
            },
        ),
    ]
