# Generated by Django 5.2.11 on 2026-02-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ou', models.CharField(help_text='Previous organizational unit (e.g., IT or IT/New)', max_length=255, verbose_name='Previous OU')),
                ('new_ou', models.CharField(help_text='New organizational unit (e.g., HR or HR/Management)', max_length=255, verbose_name='New OU')),
                ('changed_by', models.CharField(help_text='Username of admin who made the change', max_length=100, verbose_name='Changed By')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the change', verbose_name='Changed At')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', help_text='Status of the OU change operation', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the move failed', null=True, verbose_name='Error Message')),
                ('old_dn', models.CharField(blank=True, help_text='Previous Distinguished Name', max_length=255, null=True, verbose_name='Old DN')),
                ('new_dn', models.CharField(blank=True, help_text='New Distinguished Name', max_length=255, null=True, verbose_name='New DN')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ou_changes', to='Employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['employee'], name='audit_logs_employe_b48178_idx'), models.Index(fields=['changed_at'], name='audit_logs_changed_35eb1b_idx'), models.Index(fields=['status'], name='audit_logs_status_515e02_idx')],
            },
        ),
    ]
